package gu_android_team.modernbooklibrary.domain.usecases.screens

import gu_android_team.modernbooklibrary.domain.usecases.methods.AddBookToLocalDbUseCase
import gu_android_team.modernbooklibrary.domain.usecases.methods.CheckIfBookIsInDbUseCase
import gu_android_team.modernbooklibrary.domain.usecases.methods.DeleteBookByIdUseCase
import gu_android_team.modernbooklibrary.domain.usecases.methods.GetBookFromRemoteSourceUseCase


interface BookDescriptionScreenUseCase : GetBookFromRemoteSourceUseCase, AddBookToLocalDbUseCase,
    CheckIfBookIsInDbUseCase, DeleteBookByIdUseCase {
}