package gu_android_team.modernbooklibrary.domain.usecases.screens

import gu_android_team.modernbooklibrary.domain.usecases.methods.DeleteBookByIdUseCase
import gu_android_team.modernbooklibrary.domain.usecases.methods.GetBooksInCache

interface FavoritesScreenUseCase: GetBooksInCache, DeleteBookByIdUseCase {
}