package gu_android_team.modernbooklibrary.domain.usecases.screens

import gu_android_team.modernbooklibrary.domain.usecases.methods.GetSearchingBooksUseCase

interface SearchScreenUsecase : GetSearchingBooksUseCase